<a href="https://colab.research.google.com/github/TasnovaSUST/Python/blob/main/Final_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Generators

In [ ]:
def number_generator():
    for i in range(1, 4):
        yield i

# Create the generator
gen = number_generator()

# Get values from the generator
print(next(gen))
print(next(gen))
print(next(gen))

1
2
3


In [ ]:
def even_number_generator():
    for i in range(1, 10):
        if i % 2 == 0:
            yield i

gen = even_number_generator()
print(next(gen))
print(next(gen))
print(next(gen))
print(next(gen))


2
4
6
8


In [5]:
# Generator expression for squares of numbers
squares = (x**2 for x in range(1, 10))
print(next(squares))
print(next(squares))
print(next(squares))
print(next(squares))
print(next(squares))
print(next(squares))
print(next(squares))
print(next(squares))
print(next(squares))

1
4
9
16
25
36
49
64
81


In [6]:
cubes = (x**3 for x in range(1, 6))
print(next(cubes))
print(next(cubes))
print(next(cubes))
print(next(cubes))
print(next(cubes))

1
8
27
64
125


Closures

In [7]:
def outer_function(x):
    def inner_function(y):
        return x + y
    return inner_function

closure = outer_function(10)
print(closure(5))

15


In [9]:
def power_outer(x):
  def power_inner(y):
    return x**y
  return power_inner

square = power_outer(2)
print(square(10))

1024


In [11]:
def power_outer(x):
  def power_inner(y):
    return y**x
  return power_inner

cube = power_outer(3)
print(cube(10))

1000


In [17]:
def counter():
    c = 0
    def make_count():
      nonlocal c
      c += 1
      return c
    return make_count

count = counter()
print(count())
print(count())


count2 = counter()
print(count2())
print(count())

1
2
1
3


Decorators

In [30]:
def greet_decorator(func):
    def wrapper():
        print("Hello!")
        func()
        print("Nice to meet you!")
    return wrapper

@greet_decorator
def ordinary():
  print("I am Tasnova Islam")

@greet_decorator
def ordinary2():
  print("See you again")

ordinary()


Hello!
I am Tasnova Islam
Nice to meet you!


In [31]:
def greet_decorator(func):
    def wrapper():
        print("Hello!")
        func()
        print("Goodbye!")
    return wrapper

@greet_decorator
def my_function():
    print("I am learning decorators!")

my_function()

Hello!
I am learning decorators!
Goodbye!


In [33]:
from time import time

In [34]:
def timer_decorator(func):
  def wrapper():
    start_time = time()
    ret_val = func()
    end_time = time()
    print("Elapsed Time: ", end_time - start_time)
    return ret_val

  return wrapper

In [36]:
@greet_decorator
@timer_decorator
def my_function():
    print("I am learning decorators!")

my_function()

Hello!
I am learning decorators!
Elapsed Time:  1.4543533325195312e-05
Goodbye!


In [42]:
# prompt: Create a 2D NumPy array of random integers between 1 and 50.
# Perform the following:
# Find the mean of all elements.
# Transpose the array.
# Sort the array along rows.
# Extract all elements greater than 25.
# Perform matrix multiplication between the original and transposed array

import numpy as np

# Create a 2D NumPy array of random integers between 1 and 50
array_2d = np.random.randint(1, 51, size=(5, 5))  # Example: 5x5 array

# Find the mean of all elements
mean_value = np.mean(array_2d)
print("Mean of all elements:", mean_value)

# Transpose the array
transposed_array = np.transpose(array_2d)
print("\nTransposed array:\n", transposed_array)


# Sort the array along rows
sorted_array = np.sort(array_2d, axis=1)
print("\nSorted array along rows:\n", sorted_array)

# Extract all elements greater than 25
elements_greater_than_25 = array_2d[array_2d > 25]
print("\nElements greater than 25:\n", elements_greater_than_25)

# Perform matrix multiplication between the original and transposed array
matrix_product = np.matmul(array_2d, transposed_array)
print("\nMatrix product of original and transposed array:\n", matrix_product)

Mean of all elements: 26.56

Transposed array:
 [[44 17 20 37  2]
 [47 27  8 23 36]
 [38 36 19 14 24]
 [17 27  3 38 45]
 [32 28  3 38 41]]

Sorted array along rows:
 [[17 32 38 44 47]
 [17 27 27 28 36]
 [ 3  3  8 19 20]
 [14 23 37 38 38]
 [ 2 24 36 41 45]]

Elements greater than 25:
 [44 47 38 32 27 36 27 28 37 38 38 36 45 41]

Matrix product of original and transposed array:
 [[6902 4740 2125 5103 4769]
 [4740 3827 1405 3844 4233]
 [2125 1405  843 1418 1042]
 [5103 3844 1418 4982 4506]
 [4769 4233 1042 4506 5582]]
