<a href="https://colab.research.google.com/github/TasnovaSUST/Python/blob/main/Tasnova_Islam_(PP_02_08).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Grading System

In [1]:
score = input("Enter employee's score: ")
score = int(score)
if score >= 90:
    print('Excellent')
elif score >= 80:
    print('Very GOod')
elif score >= 70:
    print('Good')
elif score >= 60:
    print('Satisfactory')
elif score < 60:
    print('Needs Improvment')

Enter employee's score: 91
Excellent


2. Sum of odd number

In [7]:
# Sum of odd number_while loop
odd_sum = 0
n = input("Enter a number: ")
n = int(n)
if n < 0:
    print("Invaild input. Please enter a positive integer")
else:
    i = 1
    while i <= n:
        odd_sum = odd_sum + i
        i = i + 2
print("The sum of odd numbers is", odd_sum)


Enter a number: 10
The sum of odd numbers is 25


3.Regular Expression

In [10]:
x = "banana"
y = "Life is what happens when you're busy making other plans."
import re

# Find all occurrences of the letter 'a' in string x and print their positions
x = "banana"
for match in re.finditer("a", x):
    print("Letter 'a' found at position:", match.start())

# Replace the word "what" in string y with "where" and print the new string
y = "Life is what happens when you're busy making other plans."
new_y = re.sub("what", "where", y)
print("Modified string:", new_y)

Letter 'a' found at position: 1
Letter 'a' found at position: 3
Letter 'a' found at position: 5
Modified string: Life is where happens when you're busy making other plans.


5. NumPy

In [18]:
import numpy as np

# Create a 3x3 array with random integers between 5 and 15
arr = np.random.randint(5, 16, size=(3, 3))

# Display the array
print("Original Array:")
print(arr)

# Transpose of the array
transpose_arr = arr.T
print("\nTranspose of the Array:")
print(transpose_arr)

# Sum of all elements in the array
sum_of_elements = np.sum(arr)
print("\nSum of all elements:", sum_of_elements)

# Indices of elements greater than 10
indices = np.where(arr > 10)
print("\nIndices of elements greater than 10:")
print(list(zip(indices[0], indices[1])))

Original Array:
[[ 5  9 11]
 [ 5  7 12]
 [12 11 15]]

Transpose of the Array:
[[ 5  5 12]
 [ 9  7 11]
 [11 12 15]]

Sum of all elements: 87

Indices of elements greater than 10:
[(0, 2), (1, 2), (2, 0), (2, 1), (2, 2)]


In [19]:
arr > 10

array([[False, False,  True],
       [False, False,  True],
       [ True,  True,  True]])

4. File handing

In [15]:
with open("notes.txt", "w") as file:
    file.write("Programming is an essential skill in today's wprld.")
with open("notes.txt", "r") as file:
    content = file.read()
print(content)

Programming is an essential skill in today's wprld.


In [16]:
import os
os.remove("notes.txt")